#Plot4 R script using mydates from Reading code.R
par(mfrow = c(2,2), mar = c(2, 4, 4, 2))
plot(as.numeric(mydates$Global_active_power), type = "l", ylab = "Global Active Power", xlab = "", xaxt = "n")
axis(1, at = c(0, 1500, 2900), labels = c("Thu", "Fri", "Sat"))
plot(as.numeric(mydates$Voltage), type = "l", xlab = "datetime", ylab = "Voltage", xaxt = "n")
axis(1, at = c(0, 1500, 2900), labels = c("Thu", "Fri", "Sat"))
plot(as.numeric(mydates$Sub_metering_1), type = "l", ylab = "Energy sub meeting", xlab = "", ylim = c(0, 40), xaxt = "n", yaxt= "n", col = "black")
par(new=T)
plot(as.numeric(mydates$Sub_metering_2), type = "l", ylab = "", xlab = "", col = "red", xaxt = "n", yaxt= "n", ylim = c(0, 40))
par(new=T)
plot(as.numeric(mydates$Sub_metering_3), type = "l", ylab = "", xlab = "", col = "blue", xaxt = "n", yaxt= "n", ylim = c(0, 40))
axis(1, at = c(0, 1500, 2900), labels = c("Thu", "Fri", "Sat"))
axis(2, at = c(0, 10, 20, 30), labels = c("0", "10", "20", "30"))
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("Black", "Red", "Blue"), lty = c(1,1,1))
plot(as.numeric(mydates$Global_reactive_power), type = "l", ylab = "Global_reactive_power", xlab = "datetime", xaxt = "n")
axis(1, at = c(0, 1500, 2900), labels = c("Thu", "Fri", "Sat"))
dev.copy(png, "plot4.png")
dev.off()